"""Initial migration.

Revision ID: 245e6a7e79a9
Revises: 
Create Date: 2024-10-07 00:42:45.650311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245e6a7e79a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('seleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('elevacion', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('seccion', sa.String(length=10), nullable=False),
    sa.Column('etapa', sa.String(length=50), nullable=False),
    sa.Column('supervisor', sa.String(length=80), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seleccion')
    op.drop_table('usuario')
    # ### end Alembic commands ###
