"""Agrega columna fecha a seleccion

Revision ID: 819bb36451b0
Revises: 245e6a7e79a9
Create Date: 2024-10-07 04:21:14.760893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819bb36451b0'
down_revision = '245e6a7e79a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seleccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seleccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DATETIME(), nullable=True))
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
